requires = ["tox>=4.22"]
env_list = ["3.13", "3.12", "3.11", "3.10", "3.9", "cover", "types"]
allowlist_externals = ["coverage", "mypy"]

[env_run_base]
description = "Run test under {base_ptyhon}"
dependency_groups = ["test"]
commands = [["coverage", "run", "-p", "-m", "pytest"]]

[env.cover]
description = "combine test coverage reports"
commands = [
    ["coverage", "combine"],
    ["coverage", "report"],
]

[env.types]
description = "run type check on code base"
dependency_groups = ["types"]
commands = [["mypy", "src", "tests"]]
